#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';



use Series\Series;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

$console = new Application('My TV-Show Downloader', '0.1');

$console
    ->register('download')
    ->setDescription('Download latest episodes')
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $series = Series::createWithConfig(file_exists(__DIR__.'/../config/config.php' ? __DIR__.'/../config/config.php' : null));

        $showsDownloadable = $series->getDownloadableShowCollection();

        if (!count($showsDownloadable->getCollection())) {
            $output->writeln('<info>No new show to download</info>');
        } else {
            $output->writeln('<info>The following show will be downloaded:</info>');
            $output->writeln($showsDownloadable->getCollection());

            $series->download($showsDownloadable);
        }
    })
;

$console->run();
